on:
  push:
  workflow_dispatch:
  pull_request:
name: CI
jobs:
  CI:
    name: CI
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - name: Build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}'
      run: |
        & '.\install.ps1'
        & '.\build.ps1'
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Keep dist
        path: dist
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $tag = ($env:GITHUB_REF -split '/')[-1]
        $hubArgs = @()
        Get-ChildItem 'dist/*' | ForEach-Object {
          $hubArgs += '-a'
          $hubArgs += "$($_.FullName)"
        }
        $hubArgs = $hubArgs + @('--draft', "-m ""$tag""", """$tag""")

        hub release create @hubArgs
